# compileTest.yml
#
# basiert auf:
# Copyright (C) 2020  Armin Joachimsmeyer
# https://github.com/ArminJo/Github-Actions
#

# Das ist der Name vom workflow.
name: compileTest
on: [push, pull_request]
jobs:
  build:
    name: Test compiling for Gamebuino META
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Compile all files
      uses: ArminJo/arduino-test-compile@v3
      with:
        arduino-board-fqbn: gamebuino:samd:gamebuino_meta_native
        platform-url: https://gamebuino.com/sdk/package_gamebuino_index.json
        arduino-platform: gamebuino.samd,arduino:samd
        required-libraries: Gamebuino META
        #sketch-names: "*.ino"
        #sketch-names-find-start: "DiggerPLUS/"
        set-build-path: true
        debug-compile: true
